"use client";
import { useMemo, useState } from "react";
function Slider({ label, value, min, max, step, suffix, onChange }: { label:string; value:number; min:number; max:number; step:number; suffix?:string; onChange:(v:number)=>void }) {
  return <div className="rounded-2xl border border-line bg-black/25 p-4"><div className="mb-3 flex justify-between gap-4"><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted">{label}</p><p className="text-sm font-semibold text-white">{value.toLocaleString()}{suffix ?? ""}</p></div><input className="w-full accent-sky-400" type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/></div>;
}
export function ExecutiveModel() {
  const [fleet,setFleet]=useState(10000); const [weather,setWeather]=useState(65); const [diesel,setDiesel]=useState(4.25); const [events,setEvents]=useState(8);
  const model = useMemo(()=>{ const scale=fleet/10000; const rev=184.2*scale*(weather/65)*(events/8); const ops=(18.4*scale*(diesel/4.25))+(7.2*scale); const cost=4.27*scale+0.0009*fleet; const roi=((rev+ops)*3-cost)/cost*100; return {rev,ops,cost,roi,payback:(cost/(rev+ops))*12};},[fleet,weather,diesel,events]);
  const money=(v:number)=>`$${v>=1000?(v/1000).toFixed(1)+"B":v.toFixed(1)+"M"}`;
  return <div className="grid gap-6 lg:grid-cols-[.85fr_1.15fr]">
    <div className="mission-panel rounded-[2rem] p-7"><p className="font-mono text-xs uppercase tracking-[0.3em] text-blueIntel">Executive Analytics</p><h3 className="mt-4 text-4xl font-semibold text-white">Interactive financial model</h3><div className="mt-7 grid gap-4"><Slider label="Fleet Size" value={fleet} min={100} max={10000} step={100} onChange={setFleet}/><Slider label="Weather Severity" value={weather} min={10} max={100} step={5} suffix="%" onChange={setWeather}/><Slider label="Diesel Price" value={diesel} min={3} max={6} step={0.05} suffix="/gal" onChange={setDiesel}/><Slider label="Annual Preventable Events" value={events} min={1} max={25} step={1} onChange={setEvents}/></div></div>
    <div className="mission-panel rounded-[2rem] p-7"><div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-amberRisk/25 bg-amberRisk/10 p-5"><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted">Annual Revenue Protected</p><p className="mt-3 text-4xl font-semibold text-amberRisk">{money(model.rev)}</p></div><div className="rounded-2xl border border-greenSafe/25 bg-greenSafe/10 p-5"><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted">Annual Operating Savings</p><p className="mt-3 text-4xl font-semibold text-greenSafe">{money(model.ops)}</p></div><div className="rounded-2xl border border-blueIntel/25 bg-blueIntel/10 p-5"><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted">Payback</p><p className="mt-3 text-4xl font-semibold text-blueIntel">{model.payback.toFixed(1)} mo</p></div><div className="rounded-2xl border border-blueIntel/25 bg-blueIntel/10 p-5"><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted">3-Year ROI</p><p className="mt-3 text-4xl font-semibold text-blueIntel">{Math.round(model.roi)}%</p></div></div></div>
  </div>;
}